name: "Build and Deploy Frontend"
description: "Build Next.js frontend and deploy static export to S3"
inputs:
  bucket:
    description: "S3 bucket name to deploy to (without s3://)"
    required: true
  role_to_assume:
    description: "AWS IAM role ARN to assume"
    required: true
  cloudfront_distribution_id:
    description: "CloudFront distribution ID"
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: frontend
      run: npm ci

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: "eu-west-1"

    - name: Build
      shell: bash
      working-directory: frontend
      run: npm run build

    - name: Sync to S3
      shell: bash
      working-directory: frontend
      env:
        AWS_REGION: "eu-west-1"
      run: |
        set -euo pipefail
        aws s3 sync "dist" "s3://${{ inputs.bucket }}" --delete

    - name: Invalidate CloudFront cache
      shell: bash
      env:
        AWS_REGION: "eu-west-1"
        DISTRIBUTION_ID: ${{ inputs.cloudfront_distribution_id }}
      run: |
        set -euo pipefail
        aws cloudfront create-invalidation \
          --distribution-id "$DISTRIBUTION_ID" \
          --paths "/*"
